[package]
name = "zed-dbml"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/dbml.rs"

[dependencies]
zed_extension_api = "0.7.0"

[profile.release]
panic = "abort"
opt-level = "z"
lto = true
strip = true
