id = "dbml"
name = "DBML"
description = "DBML (Database Markup Language) support with syntax highlighting, LSP features, and intelligent code completion"
version = "0.1.0"
schema_version = 1
authors = ["Hamza Kamal<kamal.hamza@outlook.com>"]
repository = "https://github.com/kamal-hamzal/dbml-zed"
entry = "extension.wasm"

[language_servers.dbml-language-server]
name = "DBML Language Server"
language = "DBML"

[grammars.dbml]
repository = "https://github.com/dynamotn/tree-sitter-dbml"
rev = "2e2fa5640268c33c3d3f27f7e676f631a9c68fd9"

[wasm]
path = "extension.wasm"
