id = "dbml"
name = "DBML"
description = "DBML (Database Markup Language) support with syntax highlighting, LSP features, and intelligent code completion"
version = "0.1.0"
schema_version = 1
authors = ["Your Name <your.email@example.com>"]
repository = "https://github.com/yourusername/zed-dbml"

[language_servers.dbml-language-server]
name = "DBML Language Server"
language = "DBML"

[grammars.dbml]
repository = "https://github.com/dynamotn/tree-sitter-dbml"
rev = "2e2fa5640268c33c3d3f27f7e676f631a9c68fd9"  # Update this with actual latest commit
