name = "DBML"
grammar = "dbml"
path_suffixes = ["dbml"]
line_comments = ["//"]
block_comment = ["/*", "*/"]

[brackets]
"(" = ")"
"[" = "]"
"{" = "}"
"<" = ">"
"'" = "'"
"\"" = "\""
"`" = "`"

[autoclose_before]
default = ";,.|=}])>'\"`"

# Word characters for DBML identifiers
[word_characters]
default = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_"
